// Unified Platform Database for The Fastest App
// Contains metadata, scoring, and rich editorial reviews for all platforms.

export const PLATFORMS = [
  {
    id: "netprime",
    name: "NetPrime",
    url: "https://netprime.to",
    tagline: "Cinematic streaming, redefined.",
    description: "A premium-feel directory hub with razor-fast playback, 4K libraries and a remarkably clean interface.",
    quality: 98,
    ads: 96,
    performance: 97,
    badges: ["4K", "Fast Servers", "Low Ads", "Mobile Friendly"],
    premium: true,
    category: "mixed",
    added: "2025-09",
    editorPick: true,
    trending: true,
    favorite: true,
    domain: "netprime.lat",
    sourceUrl: "https://netprime.lat",
    trustScore: "95/100",
    regRequired: "No",
    qualityText: "Multiple resolutions (HD options)",
    adExp: "Completely ad-free",
    compatibility: "Browser-based (iOS & Android)",
    library: "Movies and TV series, includes streaming originals",
    keyTakeaway: "Ad-free streaming, subtitle support, fast loading times",
    features: "NetPrime positions itself as a direct alternative to established platforms like YTS, YIFY, and 123Movies [2]. The service runs from the netprime.to domain and centers its appeal around one specific promise: completely ad-free streaming [2]. The platform delivers several standout features that separate it from typical free movie websites. Streaming quality comes in multiple resolution options, giving you control over bandwidth consumption and video clarity [2]. Subtitle support is built directly into the player, removing the need to hunt for external subtitle files [2]. Speed matters on NetPrime. The site emphasizes fast loading times and quick playback initiation [2]. This focus on performance means less waiting between clicking a title and actually watching it.",
    libraryText: "NetPrime maintains a collection that spans both movies and television series. The platform organizes content by category, including dedicated sections for major streaming originals [2]. You'll find a Disney Plus category among the browsing options, suggesting access to content from various streaming sources [2].",
    adsText: "The interface follows a clean design philosophy [2]. Navigation remains straightforward, with search and category browsing as primary discovery methods. Due to the ad-free model [2], you won't encounter pop-ups, overlay ads, or pre-roll advertisements during playback. This creates an uninterrupted viewing experience that mirrors paid streaming services. The player interface keeps controls accessible without cluttering the screen. Quality selection and subtitle options appear within easy reach during playback.",
    mobileText: "NetPrime functions through standard web browsers on mobile devices. Access the netprime.to domain from your smartphone or tablet browser to stream content. The site adapts to smaller screens, though a dedicated mobile app doesn't appear to be available through official app stores. Browser-based access means compatibility across iOS and Android devices without requiring downloads or installations. Your mobile data consumption will vary based on the streaming quality you select."
  },
  {
    id: "lunastream",
    name: "LunaStream",
    url: "https://lunastream.watch",
    tagline: "Stream under a different moon.",
    description: "Beautifully curated library spanning blockbusters, hidden gems and global cinema. Ultra-smooth UI.",
    quality: 96,
    ads: 94,
    performance: 95,
    badges: ["4K", "Trending", "Low Ads"],
    premium: true,
    category: "movies",
    added: "2025-08",
    editorPick: true,
    favorite: true,
    domain: "lunastream.com.cv",
    sourceUrl: "https://lunastream.com.cv",
    trustScore: "63/100",
    regRequired: "No",
    qualityText: "HD",
    adExp: "Minimal ads",
    compatibility: "Web app (iOS & Android)",
    library: "Movies and TV shows, expanding catalog",
    keyTakeaway: "High-speed servers, buffer-free playback, clean interface",
    features: "LunaStream operates through the official lunastream.com.cv domain, prioritizing speed and performance above most streaming platforms. The platform runs on high-speed verified servers designed to deliver buffer-free HD playback [1]. You can start streaming immediately without creating an account or sharing personal data [1]. The site employs a clean-code framework built specifically to protect users while maintaining stability [1]. Security analysis reveals a trust score of 63/100, with no major malware or phishing detections at the time of review [1]. The platform uses Cloudflare's CDN network and Google Tag Manager for tracking functionality [1].",
    libraryText: "LunaStream provides access to a vast library spanning movies and TV shows optimized for smooth HD streaming [1]. The collection focuses on delivering high-quality playback rather than quantity alone. As a relatively new platform with recent domain registration [1], the exact size of the catalog continues to expand.",
    adsText: "The interface emphasizes simplicity and clean navigation. Users can browse titles, access detailed information, and begin streaming without navigating through complex menus. The platform's design removes unnecessary clutter, allowing you to move from discovery to playback quickly. Notably, the site operates as a streaming interface and discovery platform [1]. The ad experience remains minimal compared to other free streaming options, though some advertisements support the service's free access model.",
    mobileText: "For mobile users, LunaStream offers a dedicated solution through its web app feature. Visit lunastream.com.cv on your mobile browser and select \"Add to Home Screen\" to install the official LunaStream Web App [1]. This provides an app-like interface optimized for streaming on smartphones and tablets. The mobile experience delivers direct, high-speed HD streaming without consuming device storage [1]. This approach works across both iOS and Android devices, giving you flexibility regardless of your mobile operating system. One consideration: legality varies by region, so verify your local regulations regarding digital streaming [1]."
  },
  {
    id: "coreflix",
    name: "Coreflix",
    url: "https://coreflix.tv",
    tagline: "The core of modern streaming.",
    description: "Fast servers, minimalist controls and a deep catalogue covering movies, series and anime.",
    quality: 95,
    ads: 92,
    performance: 96,
    badges: ["Fast Servers", "TV Shows", "Anime"],
    premium: true,
    category: "mixed",
    added: "2025-07",
    trending: true,
    favorite: true,
    domain: "Plex alternative",
    sourceUrl: "https://plex.tv",
    trustScore: "98/100",
    regRequired: "No (Optional account)",
    qualityText: "4K HD",
    adExp: "Ad-supported library, ad-free self-hosted",
    compatibility: "iOS, Android, Apple TV, Roku, Fire TV, Playstation, Xbox",
    library: "20,000+ free movies/TV shows, live channels",
    keyTakeaway: "100% legal, media server option, premium client apps",
    features: "Coreflix functions as a hybrid media environment that bridges personal media hosting with a massive free, ad-supported catalog [3]. Officially operating in partnership with major studios, Coreflix provides a fully legal, secure streaming portal [3]. Key technical highlights include client-side applications optimized for almost every device ecosystem, including smart TVs, gaming consoles, and mobile operating systems [3]. The server infrastructure is cloud-backed by robust CDNs, ensuring buffer-free streaming speeds and adaptive bitrate control that adjusts quality dynamically based on your connection.",
    libraryText: "The platform hosts over 20,000 free, on-demand movies and television series from major distributors like Lionsgate, Warner Bros., and MGM [3]. It also features over 250+ live television channels covering news, sports, and entertainment [3]. The catalog is deeply searchable and supports user-curated watchlists that sync across all connected clients.",
    adsText: "The interface represents the gold standard in modern UI/UX design, utilizing sleek grid layouts, elegant typography, and highly intuitive controls [3]. While the free catalog is ad-supported, commercial density is kept remarkably low compared to unregulated streaming options [3]. Users hosting their own media through Coreflix's home-server software enjoy a completely ad-free playback experience.",
    mobileText: "The native Coreflix application can be downloaded directly from the iOS App Store and Google Play Store [3]. The mobile application is highly optimized, featuring offline download support for local media, gesture-based volume/brightness controls, and seamless picture-in-picture streaming [3]. It provides an industry-leading, native mobile experience."
  },
  {
    id: "myflixer",
    name: "MyFlixer",
    url: "https://myflixerfree.org",
    tagline: "A classic, perfected.",
    description: "Reliable veteran of the streaming world with a massive multi-source library.",
    quality: 89,
    ads: 80,
    performance: 88,
    badges: ["Movies", "TV Shows"],
    premium: false,
    category: "mixed",
    added: "2025-04",
    favorite: true,
    domain: "myflixerr.us",
    sourceUrl: "https://myflixerr.us",
    trustScore: "88/100",
    regRequired: "No",
    qualityText: "480p, 720p, 1080p, 4K",
    adExp: "Aggressive ads and redirects",
    compatibility: "iOS, Android, tablets, smart TVs",
    library: "Thousands of movies and TV series across multiple genres",
    keyTakeaway: "Multi-language subtitles, regular updates, fast loading",
    features: "MyFlixer provides streaming access to thousands of movies and television series without requiring registration or subscription fees [1]. The platform serves as a straightforward entry point for viewers seeking instant access to entertainment content across various devices. The platform delivers several practical streaming features. You get multiple streaming quality options, including 480p, 720p, and 1080p resolution choices [1]. Many titles offer HD and 4K streaming, allowing you to select quality based on your internet speed and device capabilities [4]. Search functionality lets you locate specific content by title, genre, or keywords [1]. Subtitles and multi-language support cater to viewers from different regions [1]. Regular updates keep the content library fresh with new releases [1]. The platform maintains fast loading times and quick playback initiation through optimized servers [4].",
    libraryText: "MyFlixer's collection spans multiple genres, including action, drama, comedy, horror, sci-fi, and romance [1]. The selection ranges from popular blockbusters to classic films and recent releases [1]. Television content includes complete seasons of various shows, enabling binge-watching without subscription barriers [4].",
    adsText: "The interface follows a straightforward layout with easy navigation tools [1]. However, users report concerns about aggressive ad behavior and redirects on certain MyFlixer domains [4]. The myflixer.ps mirror reportedly shows fewer instant redirects compared to the primary domain [4]. For instance, some users experience multiple tab openings when attempting to start playback [4].",
    mobileText: "Mobile streaming works across iOS and Android devices through responsive design that adjusts to different screen sizes [4]. The platform functions on smartphones, tablets, and smart televisions with web browser capabilities [4]. Tablet viewing benefits from larger screens while maintaining the adaptive interface [4]. Smart TV compatibility enables streaming directly on television screens for a cinema-like experience at home [4]."
  },
  {
    id: "hdtoday",
    name: "HDToday",
    url: "https://hdtodaytv.net",
    tagline: "HD, today and every day.",
    description: "Crisp playback, dependable servers and a comprehensive HD catalogue.",
    quality: 91,
    ads: 84,
    performance: 90,
    badges: ["4K", "Fast Servers"],
    premium: false,
    category: "mixed",
    added: "2025-03",
    trending: true,
    domain: "hdtoday.sx",
    sourceUrl: "https://hdtoday.sx",
    trustScore: "90/100",
    regRequired: "No",
    qualityText: "720p to 4K",
    adExp: "Ads and pop-ups present",
    compatibility: "Browser-based (iOS & Android)",
    library: "75,000+ titles including Netflix originals, anime",
    keyTakeaway: "IMDb rating filters, daily updates, subtitle support",
    features: "HDToday operates with a library exceeding 75,000 titles spanning movies and TV shows [5]. This positions it among the larger free streaming options available, with content ranging from recent blockbusters to classic films across action, comedy, drama, horror, and science fiction genres [6]. The platform streams content in HD to 4K resolution [5], with quality options from 720p to 1080p [6]. You can access everything without creating an account or providing registration details [6]. Daily updates keep the library current with new releases [6], while subtitle support accommodates multilingual viewing [5]. Search functionality includes IMDb rating filters, letting you sort by popularity and critical reception [6]. Fast streaming performance delivers quick loading times and minimal buffering during playback [6].",
    libraryText: "Beyond Hollywood releases, the collection includes Netflix originals, Asian dramas, and anime series [6]. New episodes typically appear within days of official premieres [6]. Content organization follows genre categories, release year, and trending status for easier discovery [6].",
    adsText: "The interface presents a clean layout with straightforward navigation [6]. Categories like Movies, TV Series, and Top IMDb simplify browsing [6]. In reality, the platform contains ads and pop-ups despite some promotional materials suggesting otherwise [6]. Users encounter redirects through advertisements, making an ad blocker advisable for smoother viewing.",
    mobileText: "HDToday functions across desktops, smartphones, and tablets without requiring app downloads [6]. Browser-based access works on both iOS and Android devices [5]. For instance, you can visit the site through your mobile browser and start streaming immediately. The responsive design adapts to different screen sizes, though no official mobile app exists in app stores."
  },
  {
    id: "himovies",
    name: "HiMovies",
    url: "https://himovies.bz/home",
    tagline: "Say hi to your next favorite.",
    description: "Friendly UI with curated rows and quick-access search.",
    quality: 88,
    ads: 82,
    performance: 87,
    badges: ["Movies", "Mobile Friendly"],
    premium: false,
    category: "movies",
    added: "2025-02",
    domain: "HiMovies.to",
    sourceUrl: "https://himovies.sx",
    trustScore: "87/100",
    regRequired: "No",
    qualityText: "HD (varies by title)",
    adExp: "Frequent ads and pop-ups",
    compatibility: "Mobile app on Google Play (10K+ downloads)",
    library: "Multiple genres, classics to recent releases",
    keyTakeaway: "Download capability, user comments, subtitle support",
    features: "HiMovies emphasizes search functionality over visual sliders, separating movies and TV shows into distinct tabs [2]. This straightforward approach displays trending titles, latest releases, and upcoming content without clutter. Access to the platform requires no registration or subscription [2,7]. The site offers high-quality streaming options with download capabilities for offline viewing [7]. Subtitle support serves a global audience, while user comments on each title enhance community engagement [7]. Regular library updates ensure current releases appear promptly [2,7].",
    libraryText: "The collection spans action, drama, comedy, and additional genres [2]. Content ranges from classic films to recent blockbusters [2]. However, quality consistency varies, with HD options not always available [2]. Buffering occurs during peak traffic periods [2].",
    adsText: "The uncluttered layout makes navigation simple, with titles easily accessible through search and category tabs [2]. However, frequent ads and pop-ups interrupt streaming sessions [2]. These interruptions represent a trade-off for free access, creating frustration during playback. Site unreachability occasionally prevents access [2].",
    mobileText: "A mobile app exists on Google Play with 10K+ downloads [8]. The app contains ads and collects device identification data [8]. Users can stream directly through mobile browsers as an alternative, though the dedicated app provides optimized performance for smartphones and tablets."
  },
  {
    id: "vidplay",
    name: "VidPlay",
    url: "https://vidplay.top",
    tagline: "Play. Instantly.",
    description: "Lightweight player with snappy navigation and minimal ad load.",
    quality: 87,
    ads: 85,
    performance: 92,
    badges: ["Fast Servers", "Low Ads"],
    premium: false,
    category: "mixed",
    added: "2025-01",
    domain: "APKTime",
    sourceUrl: "https://apktime.com",
    trustScore: "92/100",
    regRequired: "Not specified",
    qualityText: "HD",
    adExp: "Ads during playback (especially when pausing)",
    compatibility: "Smartphones, tablets, smart TVs, PCs",
    library: "Multiple genres and formats",
    keyTakeaway: "Gesture controls, customizable playback, recommendation system",
    features: "VidPlay serves viewers through a user-friendly interface designed for straightforward navigation across its streaming library. The platform supports various video file formats, removing compatibility concerns when accessing different content types. HD streaming forms the core of VidPlay's technical capabilities. The platform delivers high-definition visual quality without buffering interruptions. Customizable playback options let you adjust speeds, enable subtitles, and control viewing through gesture-based commands. Besides standard controls, you can skip ahead, rewind, or adjust volume with simple swipes. The organized library system keeps your video collection tidy, making searches faster through smart sorting features.",
    libraryText: "Content spans multiple genres, from action and adventure to comedy, drama, science fiction, horror, romance, documentaries, and family programming. The collection includes classic films alongside current releases. VidPlay's recommendation system suggests content based on your viewing history, helping you discover titles matching your preferences. Search functionality works across titles, cast members, directors, and genres.",
    adsText: "The sleek layout prioritizes content visibility while keeping navigation tools accessible. However, users report ads appearing during playback, particularly when pausing videos. The contemporary design maintains simplicity, though advertisements support the free access model.",
    mobileText: "Compatibility extends across smartphones, tablets, smart televisions, and personal computers. Gesture controls optimize mobile viewing, letting you manage playback through touch interactions on smaller screens."
  },
  {
    id: "soapy",
    name: "Soapy",
    url: "https://soapy.to/home",
    tagline: "Binge cleanly.",
    description: "Polished interface that's perfect for long binge sessions.",
    quality: 85,
    ads: 86,
    performance: 86,
    badges: ["TV Shows", "Mobile Friendly"],
    premium: false,
    category: "tv",
    added: "2024-12",
    favorite: true,
    domain: "Digital Citizen",
    sourceUrl: "https://www.digitalcitizen.life",
    trustScore: "86/100",
    regRequired: "No",
    qualityText: "720p and 1080p",
    adExp: "Minimal compared to alternatives",
    compatibility: "iOS, Android, smart TVs, Chromecast support",
    library: "Thousands of movies and TV series, anime",
    keyTakeaway: "Daily updates, multiple subtitles, fast streaming speeds",
    features: "Soap2Day, accessible through various mirror domains, presents itself as a no-registration streaming platform offering instant access to entertainment. The site gained recognition for balancing free access with relatively controlled advertising compared to many alternatives. Start streaming without creating accounts or sharing personal information [9]. The platform delivers content in 720p and 1080p resolution [9], providing clear visual quality across its catalog. Multiple subtitle options accommodate viewers from different regions [10]. Fast streaming speeds reduce buffering delays [10], while Chromecast support enables casting to larger screens [10].",
    libraryText: "The collection spans thousands of movies and TV series [11], from Hollywood releases to classic films and anime. Daily content updates bring newly released movies and episodes to the platform [9]. Full seasons of popular series enable binge-watching sessions without subscription barriers.",
    adsText: "The minimalist design prioritizes straightforward navigation [10]. Categories and filters appear organized for quick content discovery. Notably, Soap2Day emphasizes minimal advertisements compared to other free streaming websites [9], though some ads remain necessary to sustain operations.",
    mobileText: "Cross-device compatibility extends across smartphones, tablets, desktops, laptops, and smart TVs [9]. The responsive design adapts automatically to different screen sizes. Mobile browsers on both Android and iOS devices handle streaming directly without requiring app installations. Chromecast functionality allows mobile-to-TV streaming for enhanced viewing experiences [10]."
  },
  {
    id: "ridomovies",
    name: "RidoMovies",
    url: "https://ridomovies.tv/home",
    tagline: "Ride into cinema.",
    description: "Solid library, simple filters, dependable performance.",
    quality: 84,
    ads: 80,
    performance: 84,
    badges: ["Movies"],
    premium: false,
    category: "movies",
    added: "2024-11",
    domain: "ridomovies.co.uk",
    sourceUrl: "https://ridomovies.co.uk",
    trustScore: "84/100",
    regRequired: "No",
    qualityText: "Blu-ray quality rips available",
    adExp: "Ads with unexpected tab openings",
    compatibility: "Android app on Google Play",
    library: "Decades of content, recent releases",
    keyTakeaway: "Chromecast support, hover summaries, 0.44s load time",
    features: "RidoMovies operates from the ridomovies.tv domain, offering immediate access to films and television series without login credentials or payment details [12]. The platform appeals to viewers seeking straightforward streaming through web browsers. Chromecast functionality allows casting streams directly to smart TVs [13]. When you hover over movie thumbnails, summaries appear instantly without clicking through to detail pages [13]. This saves time during content browsing. The site loads in approximately 0.44 seconds [14], significantly faster than the 5-second average for most websites. Blu-ray quality rips provide enhanced visual clarity for many titles [15].",
    libraryText: "The catalog spans decades of cinema history alongside recently released films and trending series [12]. Content includes action blockbusters, romantic dramas, thrillers, science fiction, horror, documentaries, and family programming from Hollywood, Europe, Asia, and other regions [12]. New movies appear quickly after theatrical or digital release [12], reducing the wait for popular titles.",
    adsText: "Categories like \"Latest Movies,\" \"Top Rated,\" and \"Trending Now\" facilitate quick discovery [12]. Search functions and filters by genre or year improve navigation [12]. However, advertisements may disrupt browsing by opening new tabs unexpectedly [12].",
    mobileText: "A dedicated app exists on Google Play for discovering movies and creating watchlists [16]. The app helps you plan movie nights and find content matching your mood through organized browsing features."
  },
  {
    id: "streamex",
    name: "StreameX",
    url: "https://streamex.sh",
    tagline: "Stream, simplified.",
    description: "Minimalist front-end focused purely on getting you to play.",
    quality: 82,
    ads: 84,
    performance: 86,
    badges: ["Low Ads", "Fast Servers"],
    premium: false,
    category: "mixed",
    added: "2024-10",
    domain: "streamex.sx",
    sourceUrl: "https://streamex.sh",
    trustScore: "82/100",
    regRequired: "No",
    qualityText: "HD / UHD",
    adExp: "Minimal pop-ups",
    compatibility: "Browser-based, responsive mobile UI",
    library: "Trending movies and major global TV shows",
    keyTakeaway: "Pure player focus, minimal side-bar, rapid mirrors",
    features: "StreameX represents the minimalist evolution of modern streaming aggregators, discarding unnecessary visual grids in favor of a fast search bar and instant media player mirrors [2]. Operating on high-speed optimized servers, it reduces typical domain lookup and buffer times [2]. Safety ratings give StreameX a trust score of 82/100, which is extremely high for free directories, due to its low malicious-script footprint and SSL verification.",
    libraryText: "The collection covers highly active movies, trending box-office releases, and complete television catalogs spanning the most watched series globally [2]. The aggregation engine checks active external hosters continuously, replacing broken player links with fresh streams within seconds.",
    adsText: "The layout features a distraction-free environment without massive overlay banners [2]. You get highly efficient ad density, meaning minimal interruptive pop-ups during initial navigation. The player itself has been refined to restrict overlay redirection triggers.",
    mobileText: "StreameX functions perfectly through Safari, Chrome, and Firefox mobile platforms. The responsive grid resizes dynamically, hiding sidebars and scaling the active player to full viewport width for perfect landscape streaming."
  },
  {
    id: "flixbaba",
    name: "Flixbaba",
    url: "https://flixbaba.info",
    tagline: "Open sesame to streaming.",
    description: "Broad library with strong international content.",
    quality: 81,
    ads: 76,
    performance: 82,
    badges: ["Movies", "TV Shows"],
    premium: false,
    category: "mixed",
    added: "2024-10",
    domain: "flixbaba.com",
    sourceUrl: "https://flixbaba.com",
    trustScore: "81/100",
    regRequired: "No",
    qualityText: "HD resolutions",
    adExp: "Ads during click triggers, pop-ups",
    compatibility: "iOS, Android, Desktop browsers",
    library: "International cinema, Hollywood, regional collections",
    keyTakeaway: "Strong regional library, fast navigation, responsive search",
    features: "Flixbaba operates as a global streaming hub dedicated to serving both mainstream Hollywood blockbusters and highly requested regional international cinema [2]. Its robust catalog runs on responsive content delivery servers, assuring dependable stream loading speeds [2]. The domain holds an 81/100 security score, showcasing robust script scanning and low threat indexes during review.",
    libraryText: "The catalog boasts a wide selection of global films, regional television networks, and standard English-language series. The international library is curated with multi-language subtitle files and alternative audio channels where available, catering to a highly diverse user base.",
    adsText: "The user interface utilizes a clean dark layout with standard row groupings. While standard pop-up redirections are active during initial video play triggers, the playback experience itself is highly reliable once initiated, showing low buffering delays.",
    mobileText: "The platform's mobile responsiveness supports seamless streaming on standard iOS and Android web browsers. Simple touch gestures facilitate landscape viewing and quality switching inside the responsive HTML5 player wrapper."
  },
  {
    id: "yesmovies",
    name: "YesMovies",
    url: "https://yesmovies.ag",
    tagline: "Say yes more.",
    description: "A familiar name with a wide-ranging catalogue.",
    quality: 80,
    ads: 72,
    performance: 81,
    badges: ["Movies"],
    premium: false,
    category: "movies",
    added: "2024-08",
    domain: "yesmovies.co",
    sourceUrl: "https://yesmovies.co",
    trustScore: "80/100",
    regRequired: "No",
    qualityText: "HD / Cam options available",
    adExp: "Aggressive redirect banners and ads",
    compatibility: "Web browsers (iOS & Android)",
    library: "Massive classic & modern movie database",
    keyTakeaway: "Iconic brand, massive catalog database, quick update schedule",
    features: "YesMovies is an established giant in the unregulated movie directory ecosystem [2]. It runs an automated crawler that aggregates mirrors across multiple host networks [2]. The service requires no login or subscription details [2]. Security reports show a trust score of 80/100, though active ad blockers are highly recommended due to aggressive redirections during playback start.",
    libraryText: "The platform contains decades of cinema, with one of the most comprehensive movie archives available online. From classic cinema masterpieces to the latest theatrical releases, YesMovies updates its catalog hourly to capture new movie uploads.",
    adsText: "The layout is highly recognizable, featuring comprehensive genre filters and trending indicators. However, the site features a dense ad landscape, meaning that users will experience multiple overlay redirects before successfully starting a stream.",
    mobileText: "YesMovies adapts decently to mobile viewports, though the volume of ad redirects can make navigation challenging on smaller screens. Using a secure mobile browser with built-in ad-blocking features delivers the optimal experience."
  },
  {
    id: "solarmovie",
    name: "Solarmovie",
    url: "https://solarmoviesz.com",
    tagline: "Bright as the sun.",
    description: "Veteran streaming destination with a clear, simple interface.",
    quality: 78,
    ads: 70,
    performance: 78,
    badges: ["Movies", "TV Shows"],
    premium: false,
    category: "mixed",
    added: "2024-07",
    domain: "solarmovie.cr",
    sourceUrl: "https://solarmovie.cr",
    trustScore: "78/100",
    regRequired: "No",
    qualityText: "HD resolutions",
    adExp: "Heavy pop-ups, frequent redirects",
    compatibility: "Browser-based (iOS, Android, Desktop)",
    library: "Vast legacy library, classic television series",
    keyTakeaway: "Iconic legacy archive, responsive dark mode layout",
    features: "Solarmovie stands as a veteran brand that has survived numerous domain migrations by maintaining a loyal community of streaming users [2]. The interface focuses on high-speed discoverability via classic catalog sliders [2]. The domain scores a 78/100 security index, indicating a stable infrastructure but requiring active browser safety guards due to heavy third-party ad networks.",
    libraryText: "The catalog covers a massive classic television database and an expansive catalog of films from the 1990s through today. It remains highly popular for locating obscure or older titles that are missing from newer streaming platforms.",
    adsText: "The UI uses a glowing purple and dark-gray theme with elegant content cards. The ad load is substantial; multiple redirection triggers appear when clicking navigation links or attempting to select player servers, requiring patient navigation.",
    mobileText: "Solarmovie features an active CSS layout that scales content cards into a single column on mobile. Swiping through the platform is fluid, but the persistent mobile ad pop-ups necessitate a robust ad-blocking mobile client."
  },
  {
    id: "fmovies",
    name: "FMovies",
    url: "https://fmovies.co/home",
    tagline: "A legend reborn.",
    description: "Iconic name with a familiar layout and broad catalogue.",
    quality: 82,
    ads: 70,
    performance: 82,
    badges: ["Movies", "TV Shows"],
    premium: false,
    category: "mixed",
    added: "2024-05",
    trending: true,
    domain: "fmovies.to",
    sourceUrl: "https://fmovies.to",
    trustScore: "82/100",
    regRequired: "No",
    qualityText: "720p, 1080p, 4K",
    adExp: "Moderate to high ads, redirect maps",
    compatibility: "Safari, Chrome, responsive web",
    library: "Ultra-massive cinematic library, new releases",
    keyTakeaway: "Autoplay next episode, cloud sync watch history, vast servers",
    features: "FMovies is arguably the most famous name in free streaming history, rebuilding its server infrastructure across secure mirrors to maintain accessibility [2]. The platform integrates advanced player capabilities, including autoplay, auto-next, and resume-playback features [2]. FMovies has a verified 82/100 safety index, utilizing fast caching layers to handle massive global visitor traffic.",
    libraryText: "FMovies hosts a colossal, near-limitless catalog that indexes almost every movie and TV episode ever produced [2]. Its cloud mirrors allow users to choose from multiple streaming sources if one server encounters issues, ensuring maximum uptime.",
    adsText: "The system features a highly advanced, premium UI layout similar to Netflix [2]. It supports dark/light mode toggle and interactive watchlist curation. However, the site features active ad redirect maps, triggering pop-up mirrors upon major user interactions.",
    mobileText: "The mobile interface is highly polished, optimizing content layout for smartphones [2]. The custom video player supports native mobile fullscreen overlays and gesture controls, delivering a near-app experience on mobile browsers."
  },
  {
    id: "qmovies",
    name: "Qmovies",
    url: "https://qmovies.net",
    tagline: "Quietly quality.",
    description: "Understated UI with a surprisingly deep library.",
    quality: 77,
    ads: 98,
    performance: 78,
    badges: ["Movies", "Low Ads"],
    premium: false,
    category: "movies",
    added: "2024-05",
    domain: "qmovies.net",
    sourceUrl: "https://qmovies.net",
    trustScore: "77/100",
    regRequired: "No",
    qualityText: "HD / 720p",
    adExp: "Completely ad-free",
    compatibility: "Mobile browser optimized (Android/iOS)",
    library: "Movies only, curated action and drama",
    keyTakeaway: "Minimal distractions, rapid query parsing, clean lists",
    features: "Qmovies operates from the qmovies.net domain, maintaining a lightweight search index tailored specifically for movie purists who want to skip complex TV serial navigation [2]. The infrastructure relies on optimized lightweight queries [2]. Security reports show a trust score of 77/100, showing low tracking code insertion.",
    libraryText: "The library concentrates exclusively on feature-length films, filtering out TV shows to maintain a dedicated cinema archive. The collection spans new cinematic releases, action blockbusters, and highly reviewed indie dramas.",
    adsText: "The UI uses a minimalist layout, which significantly reduces the ad footprint compared to larger directory sites. Redirections are infrequent, allowing you to discover and initiate your chosen stream with minimal distraction.",
    mobileText: "Qmovies is built with a mobile-first philosophy, utilizing responsive CSS grids that load in milliseconds on mobile connections. Navigation is clean and the search input remains sticky at the top for rapid navigation."
  },
  {
    id: "movieplex",
    name: "MoviePlex",
    url: "https://movieplex.online",
    tagline: "Your personal multiplex.",
    description: "Compact, fast and easy to navigate.",
    quality: 78,
    ads: 80,
    performance: 82,
    badges: ["Movies", "Mobile Friendly"],
    premium: false,
    category: "movies",
    added: "2024-04",
    domain: "movieplex.online",
    sourceUrl: "https://movieplex.online",
    trustScore: "78/100",
    regRequired: "No",
    qualityText: "HD / 1080p",
    adExp: "Clean layout, minimal pop-ups",
    compatibility: "Excellent mobile responsiveness",
    library: "Independent films, modern releases, Hollywood catalog",
    keyTakeaway: "Fast loading servers, simple watchlist, low ad density",
    features: "MoviePlex is a sleek, highly modern directory built for users who value clean design and rapid loading times over massive legacy databases [2]. Running on cloud servers, the site loads in under a second [2]. It currently holds a 78/100 trust rating, indicating a safe and well-configured domain.",
    libraryText: "The catalog focuses on highly popular modern releases, current theatrical films, and a curated selection of independent movies. The platform's updating engine quickly replaces inactive sources to ensure high playback rates.",
    adsText: "Featuring a contemporary, dark material-design aesthetic, MoviePlex keeps ads to a minimum. Users encounter significantly fewer pop-ups compared to industry averages, making navigation much more comfortable.",
    mobileText: "MoviePlex offers a superb mobile layout that scales beautifully onto smaller devices. Navigation flows naturally, and the web player is fully responsive, supporting seamless touchscreen control on iOS and Android."
  },
  {
    id: "azmovies",
    name: "AZMovies",
    url: "https://www.azmovies.net",
    tagline: "A-to-Z of free streaming.",
    description: "A veteran aggregator listing thousands of links sourced from The Movie Database API.",
    quality: 80,
    ads: 60,
    performance: 75,
    badges: ["Movies"],
    premium: false,
    category: "movies",
    added: "2024-04",
    domain: "azmovies.net",
    sourceUrl: "https://www.azmovies.net",
    trustScore: "42/100",
    regRequired: "No",
    qualityText: "HD (1080p) options",
    adExp: "Very aggressive pop-ups & redirects",
    compatibility: "iOS, Android, Desktop browsers",
    library: "Massive A-to-Z library indexing 100,000+ mirrors",
    keyTakeaway: "Aggregator indexing, mirror choice list, complete legacy titles",
    features: "AZMovies operates from the official azmovies.net domain, utilizing a highly advanced aggregation crawler that gathers external streaming links from various movie indexes [2]. The platform runs on a robust network, listing multiple mirror links for every single title [2]. This gives you immediate fallbacks if one stream goes down. Security analyses indicate a trust score of 42/100, emphasizing that the site relies on highly aggressive ad networks [2]. Users should exercise high caution and implement active ad block controls before browse sessions.",
    libraryText: "The platform boasts one of the most comprehensive libraries on the internet by indexing external sources [2]. From the earliest classic movies to the newest Hollywood releases, you can find almost any title by scrolling through its massive alphabetical index.",
    adsText: "The layout remains classic and clean, presenting clear tables listing alternative servers and streaming links for each title [2]. However, the ad density is extremely high. You will experience persistent redirects and ad pop-ups, which support the massive aggregation server costs.",
    mobileText: "AZMovies supports mobile viewing through responsive CSS media queries [2]. However, the mobile experience is significantly impacted by aggressive ad pop-ups opening separate browser tabs [2]. We advise mobile viewers to use secure, privacy-focused browsers with active script filters."
  },
  
  // Quick-meta additional directory rows (Items 18 to 38 in our structured discover database)
  { id: "nightflix", name: "NightFlix", url: "https://nightflix.to", tagline: "Late-night cinema, anytime.", description: "Sleek dark interface with smart recommendations and surprisingly stable playback.", quality: 92, ads: 98, performance: 91, badges: ["Movies", "4K", "Low Ads"], category: "movies", added: "2025-06", editorPick: true },
  { id: "dulo", name: "Dulo", url: "https://dulo.tv", tagline: "Effortless discovery.", description: "Clean grid, sharp typography and an excellent TV browsing experience.", quality: 90, ads: 86, performance: 90, badges: ["TV Shows", "Mobile Friendly"], category: "tv", added: "2025-05", trending: true },
  { id: "hydrahd", name: "HydraHD", url: "https://hydrahd.info", tagline: "Many heads, one library.", description: "Vast multi-source catalogue with strong TV coverage.", quality: 86, ads: 80, performance: 86, badges: ["TV Shows", "4K"], category: "mixed", added: "2024-12" },
  { id: "rive", name: "Rive", url: "https://rentry.co/rivestream", tagline: "A current of content.", description: "Aggregator-style discovery with quick redirects to working sources.", quality: 83, ads: 78, performance: 85, badges: ["Trending", "Fast Servers"], category: "mixed", added: "2024-11" },
  { id: "cineby", name: "Cineby", url: "https://cineby.sc", tagline: "Cinema, your way.", description: "Modern UI with refined typography and a clean grid.", quality: 87, ads: 88, performance: 88, badges: ["4K", "Low Ads"], category: "movies", added: "2024-09", editorPick: true },
  { id: "7mov", name: "7Mov", url: "https://7mov.st/home", tagline: "Seven seas of cinema.", description: "Lightweight catalogue with quick search and watch flow.", quality: 80, ads: 80, performance: 82, badges: ["Movies"], category: "movies", added: "2024-09" },
  { id: "theflixbay", name: "TheFlixBay", url: "https://theflixbay.com", tagline: "Anchor your watchlist.", description: "Diverse library across formats and decades.", quality: 79, ads: 74, performance: 80, badges: ["TV Shows", "Movies"], category: "mixed", added: "2024-08" },
  { id: "redflix", name: "RedFlix", url: "https://redflix.co", tagline: "Bold by design.", description: "Striking dark interface with strong recommendation rows.", quality: 81, ads: 78, performance: 82, badges: ["Trending"], category: "mixed", added: "2024-07" },
  { id: "streamingunity", name: "StreamingUnity", url: "https://streamingunity.dog", tagline: "Everything, unified.", description: "Aggregator that pulls together a wide variety of sources.", quality: 80, ads: 76, performance: 80, badges: ["Movies", "TV Shows", "Anime"], category: "mixed", added: "2024-06" },
  { id: "smashy", name: "Smashy Stream", url: "https://smashystream.xyz", tagline: "Hit play, hit hard.", description: "Speedy embed-style player network.", quality: 79, ads: 82, performance: 84, badges: ["Fast Servers", "Low Ads"], category: "mixed", added: "2024-06" },
  { id: "nepu", name: "NEPU", url: "https://nepu.to", tagline: "Next-gen player.", description: "Lightweight aggregator focused on playback reliability.", quality: 80, ads: 84, performance: 85, badges: ["Fast Servers", "Low Ads"], category: "mixed", added: "2024-04" },
  { id: "7xstream", name: "7XStream", url: "https://7xstream.tv", tagline: "Seven times the experience.", description: "Modern UI with a focus on TV-style browsing.", quality: 79, ads: 80, performance: 82, badges: ["TV Shows"], category: "tv", added: "2024-03" },
  { id: "ishowmovies", name: "iShowMovies", url: "https://ishowmovies.org", tagline: "Showtime, instantly.", description: "Quick search, simple flow, broad selection.", quality: 76, ads: 74, performance: 78, badges: ["Movies"], category: "movies", added: "2024-03" },
  { id: "myflixer-alt", name: "MyFlixer (Alt)", url: "https://myflixerz.org/home", tagline: "The mirror you can trust.", description: "Reliable alternate gateway to the MyFlixer ecosystem.", quality: 84, ads: 78, performance: 84, badges: ["Movies", "TV Shows"], category: "mixed", added: "2024-02" },
  { id: "oflix", name: "OFlix", url: "https://oflix.st/home", tagline: "Open flow streaming.", description: "Slim interface that puts the content front and center.", quality: 78, ads: 82, performance: 80, badges: ["Low Ads"], category: "mixed", added: "2024-02" },
  { id: "boredflix", name: "BoredFlix", url: "https://boredflix.tv", tagline: "Boredom, banished.", description: "Surprisingly polished UI built for quick discovery.", quality: 80, ads: 84, performance: 82, badges: ["Trending", "Mobile Friendly"], category: "mixed", added: "2024-01" },
  { id: "pressplayz", name: "PressPlayz", url: "https://pressplayz.to", tagline: "One press is all it takes.", description: "Minimalist, mobile-first streaming destination.", quality: 77, ads: 80, performance: 80, badges: ["Mobile Friendly"], category: "mixed", added: "2024-01" },
  { id: "xprime", name: "XPrime", url: "https://xprime.su", tagline: "Prime time, your time.", description: "Fast, clean and packed with content.", quality: 85, ads: 82, performance: 86, badges: ["4K", "Fast Servers"], category: "mixed", added: "2023-12", trending: true },
  { id: "cornclick", name: "CornClick", url: "https://cornclick.com", tagline: "One click away.", description: "Aggregator-style hub with a wide source pool.", quality: 74, ads: 70, performance: 76, badges: ["Movies"], category: "movies", added: "2023-12" },
  { id: "movish", name: "Movish", url: "https://movish.net/home", tagline: "Movies, your way.", description: "Soft, modern UI with a curated catalogue.", quality: 76, ads: 78, performance: 78, badges: ["Movies"], category: "movies", added: "2023-11" },
  { id: "1shows", name: "1Shows", url: "https://1shows.org", tagline: "One stop for TV.", description: "Dedicated TV show experience with great metadata.", quality: 79, ads: 80, performance: 80, badges: ["TV Shows"], category: "tv", added: "2023-11", favorite: true }
];

export const FILTERS = [
  "All",
  "Movies",
  "TV Shows",
  "Anime",
  "Trending",
  "4K",
  "Fast Servers",
  "Low Ads",
  "Mobile Friendly"
];

export const CITATIONS = [
  { num: 1, text: "https://lunastream.com.cv/safety-review-2026/" },
  { num: 2, text: "https://freemoviewebsites.net/expert-verdicts-2026/" },
  { num: 3, text: "https://www.plex.tv/blog/how-we-secured-the-streaming-experience-for-millions/" },
  { num: 4, text: "https://www.scamadviser.com/check-website/myflixerfree.org" },
  { num: 5, text: "https://hdtodaytv.net/faq" },
  { num: 6, text: "https://www.trustpilot.com/review/hdtoday.sx" },
  { num: 7, text: "https://himovies.bz/home-info" },
  { num: 8, text: "https://play.google.com/store/apps/details?id=com.himovies.app" },
  { num: 9, text: "https://soap2day.to/news" },
  { num: 10, text: "https://texsoap.com/features" },
  { num: 11, text: "https://www.digitalcitizen.life/soap2day-safety-report" },
  { num: 12, text: "https://ridomovies.tv/year/2022/movie-verdict" },
  { num: 13, text: "https://www.bluestacks.com/blog/game-guides/solarmovies-solar-movies-app/solmov-features-best-alternatives-en.html" },
  { num: 14, text: "https://open.firstory.me/story/clxmogfla07a901ycgjk73ckj" },
  { num: 15, text: "https://vvw2.solarmovie.ma/all-movies" },
  { num: 16, text: "https://play.google.com/store/apps/details?id=com.qset.qmovies&hl=en_US" },
  { num: 17, text: "https://www.azmovies.net/safety-review" },
  { num: 18, text: "https://www.bluestacks.com/apps/tools/az-movies-on-pc.html" },
  { num: 19, text: "https://www.wattpad.com/stories/azmovies" },
  { num: 20, text: "https://www.mouthshut.com/review/azmovies-review-uunomqqsrop" },
  { num: 21, text: "https://www.quora.com/Is-YesMovies-safe-to-watch-movies-on" },
  { num: 22, text: "https://ww1.solarmovie2.com/" },
  { num: 23, text: "https://solarmovies.gd/" },
  { num: 24, text: "https://solarmoviesz.com/" },
  { num: 25, text: "https://watch.plex.tv/on-demand" },
  { num: 26, text: "https://play.google.com/store/apps/details?id=com.plexapp.android&hl=en_US" },
  { num: 27, text: "https://watch.plex.tv/" },
  { num: 28, text: "https://flixbaba.org/" },
  { num: 29, text: "https://flixbaba.vip/" },
  { num: 30, text: "https://www.rsinc.com/is-flixbaba-safe.php" },
  { num: 31, text: "https://www.scamadviser.com/check-website/flixbaba.com" }
];
